### ISSUE TITLE
hblock.molinero.dev site is not loading CSS etc (isolated to old Safari release)

### ISSUE THREAD

**Issue by LostAccount** [hectorm/hblock#106]
Hi something looks a little incomplete with the site https://hblock.molinero.dev

Does appear to be rendering as expected in Chrome Version 106.0.5249.91 (Official Build) (x86_64) but not Safari Version 13.1.2 (13609.3.5.1.5) (released with MacOS 10.13.6). Cleared Caches but issue persists. Might be that something changed on your site and this has tripped up this old Safari.

![image](https://user-images.githubusercontent.com/2214319/193449746-df60c609-53e1-4536-82af-0892bdcd2808.png)

Hope it's of some use.

**Comment by hectorm** [comment]
The hBlock website uses Subresource Integrity (SRI) to prevent JS and CSS resources from being altered, I suspect that may be the cause in this case.

Although I have not been able to reproduce it in the iOS 13 simulator inside a macOS VM, I don't have any physical Apple device to test it.

Since this behavior does not occur in any modern browser I have tested I'm not going to consider this a issue.
