### ISSUE TITLE
Australia Post | ssl.o.auspost.com.au

### ISSUE THREAD

**Issue by gyCfjSnO** [hectorm/hblock#117]
I keep getting an error in the Australia Post tracking app on Android. The error I get is `Connection issues, try again later. (Error 500)`

I checked AdGuard Home and the list I use `HaGeZi Personal Black & White` seems to be blocking `ssl.o.auspost.com.au` but I couldn't find out why.

I have opened an issue on HaGeZi's GitHub and in the interim checked `https://blocklist-tools.developerdan.com/entries/search?q=ssl.o.auspost.com.au` and found you were also blocking this domain. 

Hoping you can look into it as it might be a false positive?

**Comment by hectorm** [comment]
The domain `ssl.o.auspost.com.au` appears in [AdguardTeam/cname-trackers](https://github.com/AdguardTeam/cname-trackers), one of hBlock's sources.

If you think it is a false positive you should report it there and in case it is removed it will also be automatically removed from hBlock.

Although in my opinion the blocking of this domain is correct, since the CNAME record points to Adobe Marketing Cloud.

```
$ dig ssl.o.auspost.com.au @1.1.1.1

; <<>> DiG 9.18.10 <<>> ssl.o.auspost.com.au @1.1.1.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 11163
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;ssl.o.auspost.com.au.		IN	A

;; ANSWER SECTION:
ssl.o.auspost.com.au.	900	IN	CNAME	o.auspost.com.au.ssl.d2.sc.omtrdc.net.
o.auspost.com.au.ssl.d2.sc.omtrdc.net. 180 IN A	15.236.117.205
o.auspost.com.au.ssl.d2.sc.omtrdc.net. 180 IN A	13.37.25.97
o.auspost.com.au.ssl.d2.sc.omtrdc.net. 180 IN A	15.236.125.10

;; Query time: 50 msec
;; SERVER: 1.1.1.1#53(1.1.1.1) (UDP)
;; WHEN: Thu Jan 12 18:46:19 CET 2023
;; MSG SIZE  rcvd: 148
```
