### ISSUE TITLE
Req: Option, multiple hosts per line; 

### ISSUE THREAD

**Issue by rugabunda** [hectorm/hblock#44]
An option to use a select number of hosts per line would be nice, I use 20 hosts per line on most machines, this reduces hosts file size by 25%, and helps hosts file load times and responsiveness further as well.  It shrunk my file from 45 megabytes to 35.

exampe: 

`0.0.0.0 google.com google.ca google.co.uk microsoft.com twitter.com facebook.com`

**Comment by hectorm** [comment]
This feature is interesting, but implementing it is not as obvious as it seems, since even though hBlock produces a hosts file by default, it is capable of producing [other formats](https://github.com/hectorm/hblock/tree/master/resources/alt-formats) that do not support multiple domains per line and this approach is implemented by templates that assume one domain per line.

I will keep this issue open in case I give priority to this feature in the future.

**Comment by rugabunda** [comment]
Understandable. Adding this as a configurable "option" would preserve previous functionality; or having the choice of how many hosts per line, if you chose one, there you have it.

**Comment by hectorm** [comment]
In case you are still interested. I'm making several changes to hBlock and I've taken the opportunity to implement this feature in the [development branch](https://github.com/hectorm/hblock/tree/dev).

**Comment by hectorm** [comment]
I just released a new version that implements this feature.
