### ISSUE TITLE
make fails

### ISSUE THREAD

**Issue by mdosch** [hectorm/hblock#59]
With current master 7bb79f2823063f761af5d2edbc985887690fd47c `make` fails.

```
make     
find ./resources/tests/ -type f -name 'test-*.sh' | sort -n | xargs -n1 env -i \
        PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' \
        TEST_SHELL=''
Test - Main: "-C" short option
Test - Main: "--comment" long option
Test - Main: Default options
Test - Main: Double dash argument
Test - Main: Invalid long option
Test - Main: Invalid short option
Test - Main: "-l" short option
Test - Main: "--lenient" long option
Test - Main: "--no-lenient" long option
Test - Main: "--no-regex" long option
Test - Main: "-R" short option
Test - Main: "--redirection" long option
Test - Main: "-r" short option
Test - Main: "--regex" long option
Test - Main: "-T" short option
Test - Main: "--template" long option
Test - Main: "-W" short option
Test - Main: "--wrap" long option
Test - Stats: Suffixes

Error, values are not equal

[Actual]:

Top     Hosts   Suffix
1       12      .xn--j6w193g
2       9       .arpa
3       9       .jp
4       4       .com
5       4       .net
6       3       .org
7       1       .unknown

[Expected]:

Top     Hosts   Suffix
1       7       .xn--od0alg.xn--j6w193g
2       5       .home.arpa
3       5       .jp
4       5       .xn--j6w193g
5       4       .arpa
6       4       .com
7       4       .net
8       4       .xn--1lqs71d.jp
9       3       .org
10      1       .unknown

Test - Stats: TLDs
make: *** [Makefile:95: test] Error 123
```

**Comment by hectorm** [comment]
To pass all tests idn2 is necessary, because the test that is failing requires punycode encoding the domains in the Public Suffix List.

Could you confirm that the problem is that idn2 is not available in your system? Anyway give me more information about your environment, which shell you use and your operating system.

Do you think I should make this test optional if idn2 is not available?

Anyway if you only want to install hBlock you can skip using make. hBlock does not need any build step, as is a single shell script.

**Comment by mdosch** [comment]
I am using Debian Buster. After installing idn2 it works again, thanks.  
Was this dependency added recently?

**Comment by hectorm** [comment]
Yes, this dependency was added in the 3.0.0 version, because I created a small test suite to check that the script works correctly in all environments. It is only needed for testing, not for the functioning of the main script.
